// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odghrjftrayfqgmmwcpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZ2hyamZ0cmF5ZnFnbW13Y3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTQxMjQsImV4cCI6MjA2NjY5MDEyNH0.fYMKj_Z1EQx1kB8vw8y0Liz6yugnYIk6mw0W0K0nFQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});